config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Root path
  root to: 'pages#home'

  # User bookings list
  get '/booking/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
  get '/bookings', to: 'bookings#index', as: 'bookings'

  # User listings list
  get '/listings/user_listings', to: 'listings#user_listings', as: 'user_listings'
  get '/listing/by_action/:option', to: 'listings#list_by_action', as: 'list_by_action'


  # Furniture by ambiance
  get '/ambiances/:ambiance_id', to: 'ambiances#index', as: 'ambiances'

  # App routes
  get '/search', to: 'search#index', as: 'search'
  resources :listings do
      member do
        get '/approve', to: 'listings#approve_booking', as: 'approve'
        get '/reject', to: 'listings#reject_booking', as: 'reject'
        get '/rent', to: 'listings#rent_booking', as: 'rent'
        get '/finish', to: 'listings#finish_booking', as: 'finish'
      end

    resources :bookings, except: [:destroy, :new] do
      resources :payments, only: [:new, :create]
    end
    resources :furnitures
  end

  post '/listings/:listing_id/bookings/:booking_id/payments/new', to: 'payments#new'

  resources :deliveries, only: [:index, :show]
  get '/deliveries/accept/:id', to: 'deliveries#accept', as: 'accept_delivery'

  post '/listings/:listing_id/bookings/new', to: 'bookings#new', as: 'new_listing_booking'
  resources :bookings, only: [:destroy]

  # Messaging routes
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
        post :reply
        post :restore
        post :mark_as_read
      end
  end

  resources :messages, only: [:new, :create]
  get '/messages/listing/:listing_id/reject', to: 'messages#reject_booking', as: 'reject_booking_message'
  post '/messages/listing/:listing_id/send_message', to: 'messages#send_reject_message', as: 'send_reject_message'
  get '/messages/new/:user_id', to: 'messages#new_to', as: 'new_to'

  # App pages routes
  get '/about',   to: 'pages#about',   as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/team',    to: 'pages#team',    as: 'team'

  # Devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # Addresses routes for facebook users
  resources :addresses, only: [:new, :create]

  # Attachinary
  mount Attachinary::Engine => "/attachinary"
end

app/models/listing.rb
class Listing < ApplicationRecord
  PERIOD_OPTIONS = [3, 6, 9, 12, 18, 24]
  scope :available, ->(current_user) { where.not(user_id: current_user)  }

  include PgSearch
  pg_search_scope :global_search,
    associated_against: {
      furniture: [ :category ],
      address: [ :city ]
    }

  belongs_to :user
  has_one    :furniture,         dependent: :destroy
  has_one    :address,           dependent: :destroy
  has_many   :bookings,          dependent: :destroy
  has_many   :listing_ambiances, dependent: :destroy
  has_many   :ambiances,         through: :listing_ambiances

  validates :base_price, presence: true
  validates :period_min, presence: true
  validates :period_max, presence: true
  validates :deposit,    presence: true
  validates_inclusion_of :period_min, :in => PERIOD_OPTIONS, :allow_nil => true
  validates_inclusion_of :period_max, :in => PERIOD_OPTIONS, :allow_nil => true
  validate :check_period_min_max

  accepts_nested_attributes_for :furniture
  accepts_nested_attributes_for :address

  def check_period_min_max
    if PERIOD_OPTIONS.index(period_min) > PERIOD_OPTIONS.index(period_max)
      errors.add(:period_min, "Incorrect Period" )
    end
  end

  def self.booked?
    Booking.where(listing_id: self.id).exists?
  end

  def self.max_price
    max_price = 0
    Listing.all.each { |l| max_price = l.base_price if l.base_price > max_price }
    return max_price.round
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy, :approve_booking, :reject_booking, :rent_booking, :finish_booking]
  skip_before_action :authenticate_user!, only: [:index, :show, :search]

  def index
    params['option'].present? ? option = params['option'] : option = "available"
    @listings = list_by_action(option, policy_scope(Listing))
  end

  def show
    @results = policy_scope(Listing)
    @hash = Gmaps4rails.build_markers(@listing) do |result, marker|
      marker.lat result.address.latitude
      marker.lng result.address.longitude
      # marker.infowindow render_to_string(partial: "/results/map_box", locals: { result: result })
    end
  end

  def new
    @listing = Listing.new
    @listing.furniture = Furniture.new
    @listing.address = Address.new
    authorize @listing
  end

  def create
    @listing = Listing.create(listing_params)
    @listing.user = @listing.furniture.user = current_user
    authorize @listing
    if @listing.save
      ambiance_params[:ambiance_ids].each do |ambiance_id|
        next if ambiance_id == ""
        @listing.ambiances << Ambiance.find(ambiance_id)
      end
      redirect_to listing_path(@listing)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    if @listing.save
      @listing.ambiances.destroy_all
      ambiance_params[:ambiance_ids].each do |ambiance_id|
        next if ambiance_id == ""
        @listing.ambiances << Ambiance.find(ambiance_id)
      end
      redirect_to listing_path(@listing)
    else
      render "edit"
    end
  end

  def approve_booking
    @listing.bookings[0].workflow_step = "A"
    @listing.bookings[0].save
    if @listing.bookings.first.delivery.partner_delivery
      delivery_message = "You chose EasyMoveis partner delivery, and your furniture will be assigned to a delivery partner shortly."
    else
      delivery_message = "When are you available to come and pick it up?"
    end
    current_user.send_message(@listing.bookings[0].user,
      "Hello #{@listing.bookings[0].user.first_name}!\n I just approved your booking for #{@listing.furniture.name}! #{delivery_message} Cheers! #{current_user.first_name}",
     "Your booking was approved")
    redirect_to listings_path(option: 'pending'), notice: 'The booking was approved and the user has been informed.'
  end

  def reject_booking
    @listing.bookings[0].workflow_step = "R"
    @listing.bookings[0].save
    redirect_to reject_booking_message_path(@listing.id)
  end

  def rent_booking
    @listing.bookings[0].workflow_step = "T"
    @listing.bookings[0].save
    current_user.send_message(@listing.bookings[0].user, "Hello #{@listing.bookings[0].user.first_name}!\n Your furniture: #{@listing.furniture.name} was delivered!", "Booking delivered")
    redirect_to listings_path(option: 'waiting'), notice: 'The furniture was delivered to the client.'
  end

  def finish_booking
    @listing.bookings[0].workflow_step = "F"
    @listing.bookings[0].save
    current_user.send_message(@listing.bookings[0].user, "Hello #{@listing.bookings[0].user.first_name}!\n Your booking: #{@listing.furniture.name} was finished!", "Booking Finished")
    redirect_to listings_path(option: 'rented'), notice: 'The rental operation is finished.'
  end

  private

  def list_by_action(option, listings)
    case option
      when 'available'
        results = listings.select do |listing|
          listing.bookings.empty? == true
        end
      when 'pending'
        results = listings.select do |listing|
          listing.bookings.empty? == false && (listing.bookings[0].workflow_step == 'P' || listing.bookings[0].workflow_step == 'R')
        end
      when 'waiting'
        results = listings.select do |listing|
          listing.bookings.empty? == false && (listing.bookings[0].workflow_step == 'A')
        end
      when 'rented'
        results = listings.select do |listing|
          listing.bookings.empty? == false && (listing.bookings[0].workflow_step == 'T')
        end
      when 'finished'
        results = listings.select do |listing|
          listing.bookings.empty? == false && (listing.bookings[0].workflow_step == 'F')
        end
    end
    return results
  end

  def find_listing
    @listing = Listing.find(params[:id])
    authorize @listing
  end

  def listing_params
    params.require(:listing).permit(:base_price, :deposit, :ambiance_id, :period_min, :period_max, furniture_attributes: [:name, :description, :category, :listing_id, :user_id, photos: []], address_attributes: [:address_line, :city, :zip_code, :country, :latitude, :longitude]).permit!
  end

  def ambiance_params
    params.require(:listing).permit(ambiance_ids: [])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def find_similar(listing)
    final = []
    listing.ambiances.each do |ambiance|
      Listing.all.select {|l| l.ambiances.include?(ambiance)}.each do |result|
        final << result unless final.include?(result) || result == listing
      end
    end
    return final
  end
end

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.simple_fields_for :furniture, @listing.furniture do |furniture_form| %>
    <%= furniture_form.input :name %>
    <%= furniture_form.input :description %>
    <%= furniture_form.input :category, collection: Furniture::CATEGORY_OPTIONS %>
    <%= furniture_form.input :photos, as: :attachinary %>
  <% end %>
  <%= f.input :base_price %>
  <%= f.input :deposit %>
  <%= f.input :period_min, collection: Listing::PERIOD_OPTIONS %>
  <%= f.input :period_max, collection: Listing::PERIOD_OPTIONS  %>
  <%= f.association :ambiances, as: :check_boxes %>
  <%= f.simple_fields_for :address, @listing.address do |address_form| %>
    <%= address_form.input :address_line %>
    <%= address_form.input :zip_code %>
    <%= address_form.input :city %>
    <%= address_form.input :country %>
  <% end %>
  <%= f.button :submit, 'Save Listing',class: "btn btn-block btn-primary"  %>
<% end %>

app/views/listings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="box-white box-margin-height">
      <h2 class="text-center" style="margin-top: 5px;">Edit listing</h2>
        <%= render 'form' %> <br>
        <%= link_to 'Back', :back, class: "btn btn-default btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<br>
<h2 class="text-center">My Listings</h2>
<br>

<% if @listings %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <ul class="nav nav-pills nav-justified">
          <li id="listings-available" role="presentation"><%= link_to 'Available', listings_path(option: 'available') %></li>
          <li id="listings-pending" role="presentation"><%= link_to 'Action Pending', listings_path(option: 'pending') %></li>
          <li id="listings-waiting" role="presentation"><%= link_to 'Waiting Delivery', listings_path(option: 'waiting') %></li>
          <li id="listings-rented" role="presentation"><%= link_to 'Rented', listings_path(option: 'rented') %></li>
          <li id="listings-finished" role="presentation"><%= link_to 'Finished', listings_path(option: 'finished') %></li>
        </ul>

        <% @listings.each do |listing| %>
          <div class="listing-line">
            <div class="listing-image">
              <%= cl_image_tag listing.furniture.photos.first.path, width: 250, height: 150, crop: :fill %>
            </div>
            <div class="listing-content text-center">
              <% listing.bookings.first.nil? ? status = "V" : status = listing.bookings.first.workflow_step %>
              <strong><%= listing.furniture.name %> </strong> <br>
              Base price/mo: <%= listing.base_price %>$<br>
              <% if listing.bookings.first.nil? ==false %>
                Actual price/mo: <%= listing.bookings.first.price %>$ <br>
                Duration: <%= listing.bookings.first.duration %> months <br>
                From <%= listing.bookings.first.start_date %> to <%= listing.bookings[0].end_date %><br>
                Delivery: <%= listing.bookings.first.delivery.partner_delivery ? 'Partner delivery' : 'Self delivery' %> <br>
              <% end %>
              Status: <%= Booking.text_wkf_step(status) %><br>
            </div>
            <div class="listing-actions text-center">
              <%= link_to "Show listing", listing_path(listing), class: "btn btn-default" %>
              <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-default" if status == "V" %>
              <%= link_to "Show booking", listing_booking_path(listing, listing.bookings.first), class: "btn btn-default" if listing.bookings.first.nil? == false %>

              <%  if status == "P" %>
                <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-default" %>
                <%= link_to "Approve", approve_listing_path(listing), class: "btn btn-primary" %>
                <%= link_to "Reject", reject_listing_path(listing), class: "btn btn-default", data: { confirm: "Are you sure?" }  %>
              <% end %>
              <%= link_to "Delivered", rent_listing_path(listing), class: "btn btn-primary" if status == "A" %>
              <%= link_to "Finish", finish_listing_path(listing), class: "btn btn-primary" if status == "T"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <h5 class="text-center">You don't have any listing on the site!</h5>
<% end %>
<br>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
  <% display_option = params[:option] || 'available' %>
  $('#listings-<%= "#{display_option}" %>').addClass('active');
  <% end %>
<% end %>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="box-white box-margin-height">
      <h2 class="text-center" style="margin-top: 5px;">New listing</h2>
        <%= render 'form' %> <br>
        <%= link_to 'Back', :back, class: "btn btn-default btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/listings/search.html.erb
<div class="padded">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="box-white">
        <% word = @results.length >= 2 ? 's' : '' %>
        <h4 class="text-center" style="margin: 0"><%= @results.length %> result<%= word %> of furniture</h4>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-sm-7 col-sm-offset-1">
      <div class="box-white text-center">
        <h4 class="text-center">Filters</h4>
        <div class="btn btn-default">Filter 1</div>
        <div class="btn btn-default">Filter 2</div>
        <div class="btn btn-default">Filter 3</div>
        <div class="btn btn-default">Filter 4</div>
      </div>
      <br>
      <div class="search-results">
        <div class="card-container">
          <div class="row">
            <% @results.each do |listing| %>
              <div class="col-xs-12 col-sm-6">
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path listing.furniture.photos.first.path %>')">
                <div class="card-avatar">
                  <%= cl_image_tag avatar_image(listing.user), width: 100, height: 100, crop: :fill, gravity: :face, class: "avatar-bordered" %>
                </div>
                <div class="card-info"></div>
                <div class="card-title"><%= listing.furniture.name %></div>
                <div class="card-price"> <strong><%= listing.base_price.round%></strong> <small> $/mo</small> </div>
                <%= link_to '#', listing_path(listing), class: "card-link" %>
                </div>

              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-3">
      <div class="box-white" style="padding: 0">
        <div id="map" style="height: 600px">Map</div>
      </div>
    </div>
  </div>
</div>
<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/listings/show.html.erb
<div class="padded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1">
      <div class="box-white">
        <h2 class="text-center"><%= @listing.furniture.name %> </h2>
        <!-- Main product image -->
        <div style="padding:  20px 0px 20px 0px; margin: 0px -20px 0px -20px;">
          <div class="slider-for" style="max-height: 400px">
            <% @listing.furniture.photos.each do |photo| %>
              <%= cl_image_tag photo.path, width: 1024, height:768, crop: :fill%>
            <% end %>
          </div>
          <!-- Product image slider -->
          <div class="slider-nav" style="margin-bottom: 0px;">
            <% @listing.furniture.photos.each do |photo| %>
              <%= cl_image_tag photo.path, width: 300, height:200, crop: :fill %>
            <% end %>
          </div>
        </div>
      </div>
      <br>
      <!-- Product description -->
      <div class="box-white text-center">
        <p class="text-center">DESCRIPTION</p> <br>
        <%= @listing.furniture.description.gsub("\n", "<br>").html_safe %> <br> <br>
      </div>
      <br>
      <!-- User info -->
      <div id="user-info" class="box-white">
        <div id="user-avatar" class="text-center"><%= cl_image_tag avatar_image(@listing.user), width: 100, height: 100, crop: :fill, class: 'avatar-big' %></div>
        <div id="user-description">
          <p><%= @listing.user.first_name.upcase %><br>
          <% word = @listing.user.listings.count >= 2 ? 's' : '' %>
          <small><i>Member since <%= @listing.user.created_at.month %>/<%= @listing.user.created_at.year %> - <%= @listing.user.listings.count %> listing<%= word %> on EasyMoveis</i></small></p>
          <small><p><%= @listing.user.description %></p></small>
        </div>
      </div> <br>
      <!-- List of ambiances -->
      <div class="box-white text-center">
        <p class="text-center">AMBIANCES</p> <br>
        <% @listing.ambiances.each do |ambiance| %>
          <div class="btn btn-default">  <%=ambiance.name%></div>
        <%end%>
      </div>
      <br>
      <!-- Product in similar ambiance -->
      <div class="box-white">
        <p class="text-center">SEE ALSO IN THE SAME AMBIANCE</p> <br>
        <div class="autoplay" style= "padding:  20px 0px 20px 0px; margin: 0px -20px 0px -20px;">
        <% find_similar(@listing).each do |l| %>
          <%= link_to listing_path(l) do %>
            <%= cl_image_tag l.furniture.photos.first.path, width: 300, height:200, crop: :fill %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4 text-center" >
      <div class="box-white">
        <p class="text-center">STATUS</p>
        <% booking = Booking.where(listing_id: @listing.id) %>
        <div class="product-main-info" style="font-size: 18px">
          <% if @listing.bookings.first.nil? %>
            Available
          <% elsif @listing.bookings.first.workflow_step == 'T' %>
            Rented until <%= @listing.bookings.first.end_date %>
          <% else %>
            <%= Booking.text_wkf_step(@listing.bookings.first.workflow_step) %>
          <% end %>
        </div>
        <div class="product-info-separation"></div>

        <p class="text-center">LOCATION</p>
        <div class="product-main-info" id="location" style="font-size: 20px"><%= @listing.address.city + ', ' + @listing.address.country %></div>
        <div class="product-info-separation"></div>

        <p class="text-center">DEPOSIT</p>
        <div class="product-main-info"><%= @listing.deposit %>$</div>  <small>refundable</small>
        <div class="product-info-separation"></div>

        <p class="text-center">BASE PRICE</p>
        <div class="product-main-info product-base-price"><%= @listing.base_price.round %>$</div>  <small>per month</small>
        <div class="product-info-separation"></div>

        <p class="text-center">RENTAL DURATION</p>
        <div class="btn-group">
          <% Listing::PERIOD_OPTIONS.each do |duration|
            next if duration < @listing.period_min || duration > @listing.period_max%>
            <button class="btn-round-bordered text-center btn-duration" id="<%= duration %>"><%= duration %>m</button>
          <% end %>
        </div>
        <div class="product-info-separation"></div>

        <p class="text-center">ACTUAL PRICE</p>
        <div class="product-main-info" id="actual_price"><p style="font-size: 14px;">Select duration to see price</p></div><div class="product-main-info hidden" id="dollar-sign">$</div>  <small>per month</small><br><br>


<!--         <p class="text-center">RENTAL DURATION</p>
        <small>from</small><div class="product-main-info"><%= @listing.period_min %></div> <small> to </small><div class="product-main-info"> <%#= @listing.period_max %></div><small> months</small>
        <div class="product-info-separation"></div> -->

        <% if current_user != Listing.find(params[:id]).user %>
          <%= link_to 'Ask a question', new_to_path(@listing.user), class: 'btn btn-block btn-default' %> <br>
          <% if @listing.bookings.first.nil? %>
            <%= simple_form_for :booking, url: new_listing_booking_path(@listing.id) do |f| %>
              <%= f.input :duration, as: :hidden %>
              <%= f.input :price, as: :hidden %>
              <%= f.button :submit, value: 'Book!', class: "btn btn-block btn-primary" %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to "Edit listing", edit_listing_path(@listing), class: "btn btn-default btn-block"  %>
        <% end %>
      </div>
      <div id="map" style="height: 300px"></div>
    </div>
  </div>
</div>





<% content_for(:after_js) do %>
  <!-- Map builder -->
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>

  <!-- Duration/price choice -->
  <%= javascript_tag do %>
    $('.btn-duration').click(function(e) {
      $('#dollar-sign').removeClass('hidden');
      $('.btn-duration.target').removeClass('target');
      $(this).addClass('target');
      selectedPeriod= '';
      selectedPeriod=$(this).attr('id');
      $('#booking_duration').val(selectedPeriod);
      basePrice = parseInt(<%= @listing.base_price.round %>);
      var newPrice;

      if (selectedPeriod == 3) {newPrice = basePrice;}
      if (selectedPeriod == 6) {newPrice = basePrice * 0.95;}
      if (selectedPeriod == 9) {newPrice = basePrice * 0.9;}
      if (selectedPeriod == 12) {newPrice = basePrice * 0.85;}
      if (selectedPeriod == 18) {newPrice = basePrice * 0.80;}
      if (selectedPeriod == 24) {newPrice = basePrice * 0.75;}
      $('#actual_price').html(newPrice);
      $('#booking_price').val(newPrice);
    });
  <% end %>

  <!-- Slick slideshows -->
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('.slider-for').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        fade: true,
        asNavFor: '.slider-nav'
      });
      $('.slider-nav').slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        asNavFor: '.slider-for',
        dots: true,
        centerMode: true,
        focusOnSelect: true
      });
      $('.autoplay').slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
      });
    });
  <% end %>
<% end %>