config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Root path
  root to: 'pages#home'

  # User bookings list
  get '/booking/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
  get '/bookings', to: 'bookings#index', as: 'bookings'

  # User listings list
  get '/listings/user_listings', to: 'listings#user_listings', as: 'user_listings'
  get '/listing/by_action/:option', to: 'listings#list_by_action', as: 'list_by_action'


  # Furniture by ambiance
  get '/ambiances/:ambiance_id', to: 'ambiances#index', as: 'ambiances'

  # App routes
  get '/search', to: 'search#index', as: 'search'
  resources :listings do
      member do
        get '/approve', to: 'listings#approve_booking', as: 'approve'
        get '/reject', to: 'listings#reject_booking', as: 'reject'
        get '/rent', to: 'listings#rent_booking', as: 'rent'
        get '/finish', to: 'listings#finish_booking', as: 'finish'
      end

    resources :bookings, except: [:destroy, :new] do
      resources :payments, only: [:new, :create]
    end
    resources :furnitures
  end

  post '/listings/:listing_id/bookings/:booking_id/payments/new', to: 'payments#new'

  resources :deliveries, only: [:index, :show]
  get '/deliveries/accept/:id', to: 'deliveries#accept', as: 'accept_delivery'

  post '/listings/:listing_id/bookings/new', to: 'bookings#new', as: 'new_listing_booking'
  resources :bookings, only: [:destroy]

  # Messaging routes
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
        post :reply
        post :restore
        post :mark_as_read
      end
  end

  resources :messages, only: [:new, :create]
  get '/messages/listing/:listing_id/reject', to: 'messages#reject_booking', as: 'reject_booking_message'
  post '/messages/listing/:listing_id/send_message', to: 'messages#send_reject_message', as: 'send_reject_message'
  get '/messages/new/:user_id', to: 'messages#new_to', as: 'new_to'

  # App pages routes
  get '/about',   to: 'pages#about',   as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/team',    to: 'pages#team',    as: 'team'

  # Devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # Addresses routes for facebook users
  resources :addresses, only: [:new, :create]

  # Attachinary
  mount Attachinary::Engine => "/attachinary"
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box,          only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <div class="row">
    <div class="col-sm-2 text-center">
      <p><%= render 'conversations/participants', conversation: conversation %></p>
    </div>
    <div class="col-sm-10">
    <%= link_to conversation.subject, conversation_path(conversation) %>

    <div class="btn-group-vertical pull-right">
      <% if conversation.is_trashed?(current_user) %>
        <%= link_to restore_conversation_path(conversation), method: :post do %>
          <i class="fa fa-inbox"></i>
        <% end %>
      <% else %>
        <%= link_to conversation_path(conversation), method: :delete, data: {confirm: 'Are you sure?'}  do %>
         <i class="fa fa-trash-o"></i>
        <% end %>
      <% end %>

        <% if conversation.is_unread?(current_user) %>
          <br> <%= link_to mark_as_read_conversation_path(conversation), method: :post do %>
            <i class="fa fa-check"></i>
          <% end %>
      <% end %>
    </div>



    <p><%= conversation.last_message.body %>
      <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>

    </div>
  </div>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= cl_image_tag avatar_image(participant), width: 100, height: 100, crop: :fill, gravity: :face, class: "avatar" %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="padded">

        <div class="row">
          <div class="col-sm-2">
            <ul class="list-group-item nav nav-pills nav-stacked">
              <%= mailbox_section 'inbox', @box %>
              <%= mailbox_section 'sent', @box %>
              <%= mailbox_section 'trash', @box %>
            </ul>
          </div>
          <div class="col-sm-10">
            <% if @box == 'trash' %>
            <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                           data: {confirm: 'Are you sure?'} %></p>
          <% end %>
            <ul class="list-group">
              <%= render partial: 'conversations/conversation', collection: @conversations %>
            </ul>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="padded">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-sm-6"><h5><%= @conversation.subject %></h5>  </div>
            <div class="col-sm-6" style="text-align: right">Chatting with
              <%= render 'conversations/participants', conversation: @conversation %></div>
          </div>
        </div>
        <div class="panel-body">
          <div class="messages">
            <% @conversation.receipts_for(current_user).each do |receipt| %>
              <div class="media">
                <% message = receipt.message %>
                <div class="media-left">
                  <%= cl_image_tag avatar_image(message.sender), width: 100, height: 100, crop: :fill, gravity: :face, class: "avatar" %>
                </div>

                <div class="media-body">
                  <h6 class="media-heading"><%= message.sender.name %>
                    says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
                  <%= message.body %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= form_tag reply_conversation_path(@conversation), method: :post do %>
        <div class="form-group">
          <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
        </div>
        <%= submit_tag "Send Message", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>