config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Root path
  root to: 'pages#home'

  # User bookings list
  get '/booking/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
  get '/bookings', to: 'bookings#index', as: 'bookings'

  # User listings list
  get '/listings/user_listings', to: 'listings#user_listings', as: 'user_listings'
  get '/listing/by_action/:option', to: 'listings#list_by_action', as: 'list_by_action'


  # Furniture by ambiance
  get '/ambiances/:ambiance_id', to: 'ambiances#index', as: 'ambiances'

  # App routes
  get '/search', to: 'search#index', as: 'search'
  resources :listings do
      member do
        get '/approve', to: 'listings#approve_booking', as: 'approve'
        get '/reject', to: 'listings#reject_booking', as: 'reject'
        get '/rent', to: 'listings#rent_booking', as: 'rent'
        get '/finish', to: 'listings#finish_booking', as: 'finish'
      end

    resources :bookings, except: [:destroy, :new] do
      resources :payments, only: [:new, :create]
    end
    resources :furnitures
  end

  post '/listings/:listing_id/bookings/:booking_id/payments/new', to: 'payments#new'

  resources :deliveries, only: [:index, :show]
  get '/deliveries/accept/:id', to: 'deliveries#accept', as: 'accept_delivery'

  post '/listings/:listing_id/bookings/new', to: 'bookings#new', as: 'new_listing_booking'
  resources :bookings, only: [:destroy]

  # Messaging routes
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
        post :reply
        post :restore
        post :mark_as_read
      end
  end

  resources :messages, only: [:new, :create]
  get '/messages/listing/:listing_id/reject', to: 'messages#reject_booking', as: 'reject_booking_message'
  post '/messages/listing/:listing_id/send_message', to: 'messages#send_reject_message', as: 'send_reject_message'
  get '/messages/new/:user_id', to: 'messages#new_to', as: 'new_to'

  # App pages routes
  get '/about',   to: 'pages#about',   as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/team',    to: 'pages#team',    as: 'team'

  # Devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # Addresses routes for facebook users
  resources :addresses, only: [:new, :create]

  # Attachinary
  mount Attachinary::Engine => "/attachinary"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_one :furniture, through: :listing
  has_one :delivery,  dependent: :destroy

  validates :start_date, presence: true
  validates :end_date,   presence: true
  validates :user,       uniqueness: { scope: :listing, message: "should happen once per user" }
  validate  :start_date_before_past

  accepts_nested_attributes_for :delivery

  # Converting status into a text
  @workflowstep_list = {'E' => "Editing",
                      'R' => 'Rejected',
                      'D' => 'Closed',
                      'P' => 'Pending Approval',
                      'C' => 'Canceled',
                      'A' => 'Approved',
                      'T' => 'Rented',
                      'F' => 'Finished',
                      'V' => 'Available'}

  # Search for the booking and recovers its status
  def self.text_wkf_step(step)
    resp = step.nil? ? 'Available' : @workflowstep_list[step]
  end

  private

  def start_date_before_past
    unless self.start_date.nil?
      errors.add(:start_date, "The start date can't be in less than three days") if self.start_date < Date.today + 3
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking,  only: [:show, :edit, :update, :destroy, :cancel_booking]
  before_action :get_listing,   only: [:show, :edit]
  before_action :find_listing,  only: [:new, :create, :update]
  before_action :get_furniture, only: [:new, :edit]

  def index
    params['option'].present? ? option = params['option'] : option = "pending"
    @bookings = list_by_action(option, policy_scope(Booking))
  end

  def show
  end

  def new
    if current_user.bookings.where(listing_id: (params[:listing_id]) ).present?
      redirect_to listing_path(params[:listing_id]), alert: 'This listing is already booked.'
    end
    unless params[:booking][:duration].present?
      redirect_to listing_path(params[:listing_id]), alert: 'Please inform rental duration.'
    end
    @price = params[:booking][:price].to_i
    @duration = params[:booking][:duration].to_i
    @booking = @listing.bookings.new
    @booking.build_delivery
    authorize @booking
  end

   def create
    @booking = @listing.bookings.new(booking_params)
    @booking.delivery.status = "P"
    @booking.workflow_step = "P"
    @booking.user = current_user
    authorize @booking
    if @booking.save
      current_user.send_message(@listing.user, "Hey #{@listing.user.first_name}!\n I want to book #{@listing.furniture.name}! Please accept my demand as soon as possible! \n Cheers! \n #{current_user.first_name}", "You have a new booking!")
      redirect_to new_listing_booking_payment_path(@booking.listing, @booking), notice: 'Your booking was successfully created.'
    else
      @price = booking_params[:price].to_i
      @duration = booking_params[:duration].to_i
      render :new
    end
  end

  def edit
  end

  def update
    @booking.workflow_step = "P"
    authorize @booking
    @booking.update(booking_params)
    redirect_to bookings_path, notice: 'Booking was successfully updated.'
  end

  def destroy
    @booking.destroy
      redirect_to root_path, notice: 'Booking was successfully canceled.'
  end

  private

  def list_by_action(option, bookings)
    case option
      when 'pending'
        results = bookings.select do |booking|
          booking.nil? == false && (booking.workflow_step == 'P' || booking.workflow_step == 'R')
        end
      when 'waiting'
        results = bookings.select do |booking|
          booking.nil? == false && (booking.workflow_step == 'A')
        end
      when 'rented'
        results = bookings.select do |booking|
          booking.nil? == false && (booking.workflow_step == 'T')
        end
      when 'finished'
        results = bookings.select do |booking|
          booking.nil? == false && (booking.workflow_step == 'F')
        end
    end
    return results
  end

  def find_listing
    @listing = Listing.find(params[:listing_id])
  end

  def get_listing
    @listing = @booking.listing
  end

  def get_furniture
    @furniture = @listing.furniture
  end

  def find_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:end_date, :start_date, :workflow_step, :price, :duration, :user_id, :listing_id, delivery_attributes: [:partner_delivery, :delivery_price])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@listing, @booking] do |f| %>
  <%= f.error_notification %>
  <p class="text-center">START DATE</p>
  <%= f.input :start_date, as: :date_picker, label: false, placeholder: 'dd/mm/yyyy', required: true  %>
  <%= f.input :end_date, as: :date_picker, as: :hidden, placeholder: 'dd/mm/yyyy'  %>
  <%= f.input :price, as: :hidden %>
  <%= f.input :duration, as: :hidden %>
  <div id="end-date-div" class="hidden">
    <div class="product-info-separation"></div>
    <p class="text-center">END DATE</p>
    <div class="text-center"><div class="product-main-info" id="end_date"></div></div>
  </div>
  <br>
  <div id="delivery-info">
    <%= f.simple_fields_for :delivery do |ff| %>
      <div class="product-info-separation"></div>
      <p class="text-center">DELIVERY METHOD</p>
      <%= ff.input :partner_delivery, label: 'Partner delivery', as: :select, include_blank: false, label: false, :collection => [['I will arrange my delivery','false'],['I choose EasyMoveis partner delivery','true']] %>
      <p class="text-center" id="delivery-description">If you choose partner delivery, An EasyMoveis partner will deliver your furniture to your door for </p>
      <small><p class="text-center"><i>See below for details</i></p></small>
      <%= ff.input :delivery_price, as: :hidden %>
      <br>
    <% end %>
  </div>

  <%= f.button :submit, 'Book!', class: "btn btn-block btn-primary" %>
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="box-white box-margin-height">
      <h2 class="text-center" style="margin-top: 5px;">Edit booking</h2>
        <%= render 'form' %> <br>
        <%= link_to 'Back', :back, class: "btn btn-default btn-block" %>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('#delivery-info').hide();
    });
  <% end %>

  <%= javascript_tag do %>
    $('#booking_start_date').focusout(function() {
      var a = $('#booking_start_date').val();
      var parts = a.split("/");
      var startDate = new Date(parseInt(parts[2], 10),
                        parseInt(parts[1], 10) - 1,
                        parseInt(parts[0], 10));
      var endDate = new Date(new Date(startDate).setMonth(startDate.getMonth()+ <%= @duration %>));

      var dd = endDate.getDate();
      var mm = endDate.getMonth()+1;
      var yyyy = endDate.getFullYear();

      if (dd < 10) {
          dd = '0' + dd;
      }
      if (mm < 10){
          mm = '0' + mm
      }
      var endDate = dd+'/'+mm+'/'+yyyy;
      $('#booking_end_date').val(endDate);
      $("#end-date-div").removeClass('hidden');
      $("#end_date").html(endDate);
    });
  <% end %>
<% end %>

app/views/bookings/index.html.erb
<br>
<h2 class="text-center">My Bookings</h2>
<br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <ul class="nav nav-pills nav-justified">
        <li id="bookings-pending" role="presentation"><%= link_to 'Pending', bookings_path(option: 'pending') %></li>
        <li id="bookings-waiting" role="presentation"><%= link_to 'Waiting for delivery', bookings_path(option: 'waiting') %></li>
        <li id="bookings-rented" role="presentation"><%= link_to 'Rented', bookings_path(option: 'rented') %></li>
        <li id="bookings-finished" role="presentation"><%= link_to 'Finished', bookings_path(option: 'finished') %></li>
      </ul>
      <% if @bookings %>
        <% @bookings.each do |booking| %>
          <div class="listing-line">
            <div class="listing-image">
              <%= cl_image_tag booking.listing.furniture.photos.first.path, width: 250, height: 150, crop: :fill %>
            </div>
            <div class="listing-content text-center">
              <strong><%= booking.listing.furniture.name %> </strong> <br>
              Booked price/month: <%= booking.price %>$ <br>
              Duration: <%= booking.duration %> months <br>
              From <%= booking.start_date %> to <%= booking.end_date %><br>
              Status: <%= Booking.text_wkf_step(booking.workflow_step) %><br>
              Delivery: <%= booking.delivery.partner_delivery ? 'Partner delivery' : 'Self delivery' %> <br>
            </div>
            <div class="listing-actions text-center">
            </div>
            <div class="listing-actions text-center">
              <%= link_to "Show booking", listing_booking_path(booking.listing_id,booking.id), class: "btn btn-default"  %>
              <% if booking.workflow_step == "P" || booking.workflow_step == "R"%>
                <%= link_to "Edit", edit_listing_booking_path(booking.listing_id,booking.id), class: "btn btn-default"  %>
                <%= link_to "Delete", booking_path(booking.id), method: :delete, class: "btn btn-red", data: { confirm: 'Are you sure?' }   %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <h5 class="text-center">You don't have any new booking!</h5>
      <% end %>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
  <% display_option = params[:option] || 'pending' %>
  $('#bookings-<%= "#{display_option}" %>').addClass('active');
  <% end %>
<% end %>

app/views/bookings/new.html.erb
<% unless current_user.address %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="box-white box-margin-height">
        <h2 class="text-center" style="margin-top: 5px;">Please create an address to perform a booking</h2>
          <%= link_to "New address", new_address_path, class: "btn btn-block btn-default" %> <br>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="box-white box-margin-height">
          <h3 class="text-center" style="margin-top: 5px;">Book <%= @booking.listing.furniture.name %></h3>
          <div class="product-info-separation"></div>
          <p class="text-center">DEPOSIT</p>
          <div class="text-center"><div class="product-main-info" id="duration"><%= @booking.listing.deposit %>$</div> <small>refundable</small></div>
          <div class="product-info-separation"></div>
          <p class="text-center">DURATION</p>
          <div class="text-center"><div class="product-main-info" id="duration"><%= @duration %></div> <small>months</small></div>
          <div class="product-info-separation"></div>
          <p class="text-center">PRICE PER MONTH</p>
          <div class="text-center"><div class="product-main-info" id="duration"><%= @price %>$</div>   <small>per month</small></div>
          <div class="product-info-separation"></div>

          <%= render 'form' %> <br>
          <%= link_to 'Back', :back, class: "btn btn-clear btn-block" %> <br>
        </div>
        <div class="box-white box-margin-height">
          <p class="text-center">APPROXIMATE DISTANCE</p>
          <div class="text-center"><div class="product-main-info" id="delivery-length"></div></div>
          <div class="product-info-separation"></div>
          <p class="text-center">EASYMOVEIS DELIVERY PRICE</p>
          <div class="text-center"><div class="product-main-info" id="delivery-price"></div></div>
          <div class="product-info-separation"></div>
          <div id="map" style="height: 300px"></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% content_for(:after_js) do %>

  <!-- Auto end-date calculation -->
  <%= javascript_tag do %>
    $('#booking_start_date').focusout(function() {
      var a = $('#booking_start_date').val();
      var parts = a.split("/");
      var startDate = new Date(parseInt(parts[2], 10),
                        parseInt(parts[1], 10) - 1,
                        parseInt(parts[0], 10));
      var endDate = new Date(new Date(startDate).setMonth(startDate.getMonth()+ <%= @duration %>));

      var dd = endDate.getDate();
      var mm = endDate.getMonth()+1;
      var yyyy = endDate.getFullYear();

      if (dd < 10) {
          dd = '0' + dd;
      }
      if (mm < 10){
          mm = '0' + mm
      }
      var endDate = dd+'/'+mm+'/'+yyyy;
      $('#booking_end_date').val(endDate);
      $("#end-date-div").removeClass('hidden');
      $("#end_date").html(endDate);
    });
  <% end %>

  <!-- Add price and duration to form -->
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('#booking_price').val(<%= @price %>);
      $('#booking_duration').val(<%= @duration %>);
    });
  <% end %>

  <!-- Itinerary calculation -->
  <%= javascript_tag do %>
    $(document).ready(function(){
      var directionsDisplay;
      var directionsService = new google.maps.DirectionsService();

      directionsDisplay = new google.maps.DirectionsRenderer();
      var mapCenter = new google.maps.LatLng(<%= @listing.address.latitude %>, <%= @listing.address.longitude %>);
      var mapOptions = {
        zoom:11,
        center: mapCenter
      }
      map = new google.maps.Map(document.getElementById("map"), mapOptions);
      directionsDisplay.setMap(map);

      var startAddress = new google.maps.LatLng(<%= @listing.address.latitude %>, <%= @listing.address.longitude %>);
      var endAddress = new google.maps.LatLng(<%= current_user.address.latitude %>, <%= current_user.address.longitude %>);
      var request = {
        origin: startAddress,
        destination: endAddress,
        travelMode: google.maps.TravelMode.DRIVING,
      }
      directionsService.route(request, function(result, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          var routeLength = result.routes[0].legs[0].distance;
          directionsDisplay.setDirections(result);
          $('#delivery-length').append(routeLength.text);
          var deliveryPrice = Math.round(routeLength.value / 100);
          $('#delivery-price').append(deliveryPrice+'$');
          $('#delivery-description').append(deliveryPrice+'$');
          $('#booking_delivery_attributes_delivery_price').val(deliveryPrice);
        }
      });


    });
    <% end %>
  <% end %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="box-white box-margin-height">
        <h3 class="text-center" style="margin-top: 5px;">Booking for <%= @booking.listing.furniture.name %></h3>
        <%= cl_image_tag @booking.listing.furniture.photos.first.path, width: 800, height:400, crop: :fill, class: 'img-responsive' %>
        <div class="product-info-separation"></div>
        <p class="text-center">STATUS</p>
        <div class="text-center"><div class="product-main-info" id="duration"><%= Booking.text_wkf_step(@booking.workflow_step) %></div></div>
        <div class="product-info-separation"></div>
        <p class="text-center">OFFERED BY</p>
        <div class="text-center">
          <div class="product-main-info" id="duration"><%= @booking.listing.user.name %></div> <br>
          <%= @booking.listing.address.address_line %> <br>
          <%= @booking.listing.address.city %>, <%= @booking.listing.address.zip_code %> <br>
        </div>
        <div class="product-info-separation"></div>
        <p class="text-center">RENTED BY</p>
        <div class="text-center">
          <div class="product-main-info" id="duration"><%= @booking.user.name %></div> <br>
          <%= @booking.user.address.address_line %> <br>
          <%= @booking.user.address.city %>, <%= @booking.user.address.zip_code %> <br>
        </div>
        <div class="product-info-separation"></div>
        <p class="text-center">BOOKING DATES</p>
        <div class="text-center"><small>from </small><div class="product-main-info"> <%= @booking.start_date %> </div><small> to </small><div class="product-main-info"> <%= @booking.end_date %> </div></div>
        <div class="product-info-separation"></div>
        <p class="text-center">DURATION</p>
        <div class="text-center"><div class="product-main-info" id="duration"><%= @booking.duration %></div> <small>months</small></div>
        <div class="product-info-separation"></div>
        <p class="text-center">PRICE PER MONTH</p>
        <div class="text-center"><div class="product-main-info" id="duration"><%= @booking.price %>$</div> <small>per month</small></div>
        <div class="product-info-separation"></div>
        <p class="text-center">DEPOSIT</p>
        <div class="text-center"><div class="product-main-info" id="duration"><%= @booking.listing.deposit %>$</div> <small>refundable</small></div>
        <div class="product-info-separation"></div>
        <p class="text-center">DELIVERY</p>
        <div class="text-center"><div class="product-main-info"><%= @booking.delivery.partner_delivery ? "Partner delivery for #{@booking.delivery.delivery_price}$" : 'Self delivery' %></div></div>
        <div class="product-info-separation"></div>
        <div id="map" style="height: 300px"></div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <!-- Itinerary calculation -->
  <%= javascript_tag do %>
    $(document).ready(function(){
      var directionsDisplay;
      var directionsService = new google.maps.DirectionsService();

      directionsDisplay = new google.maps.DirectionsRenderer();
      var mapCenter = new google.maps.LatLng(<%= @booking.listing.address.latitude %>, <%= @booking.listing.address.longitude %>);
      var mapOptions = {
        zoom:11,
        center: mapCenter
      }
      map = new google.maps.Map(document.getElementById("map"), mapOptions);
      directionsDisplay.setMap(map);

      var startAddress = mapCenter;
      var endAddress = new google.maps.LatLng(<%= @booking.user.address.latitude %>, <%= @booking.user.address.longitude %>);
      var request = {
        origin: startAddress,
        destination: endAddress,
        travelMode: google.maps.TravelMode.DRIVING,
      }
      directionsService.route(request, function(result, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          var routeLength = result.routes[0].legs[0].distance;
          directionsDisplay.setDirections(result);
          $('#delivery-length').append(routeLength.text);
          var deliveryPrice = Math.round(routeLength.value / 100);
          $('#delivery-price').append(deliveryPrice+'$');
          $('#delivery-description').append(deliveryPrice+'$');
          $('#booking_delivery_attributes_delivery_price').val(deliveryPrice);
        }
      });
    });
    <% end %>
  <% end %>

app/views/bookings/user_bookings.html.erb
<br>
<h2 class="text-center">My Listings</h2>
<br>
<% if @bookings %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <% @bookings.each do |booking| %>
          <div class="listing-line">
            <div class="listing-image">
              <%= cl_image_tag booking.listing.furniture.photos.first.path, width: 250, height: 150, crop: :fill %>
            </div>
            <div class="listing-content text-center">
              <strong><%= booking.listing.furniture.name %> </strong> <br>
              Category: <%= booking.listing.furniture.category %> <br>
              Description; <%= booking.listing.furniture.description %><br>
              Start-date: <%= booking.start_date %><br>
              End-date: <%= booking.end_date %><br>
              Status: <%= Booking.text_wkf_step(booking.workflow_step) %><br>
            </div>
            <div class="listing-actions text-center">
            </div>
          </div>
        <% end %>
        <br>
        <%= link_to 'Back', :back %> |
      </div>
    </div>
  </div>
<% else %>
  <h3>You don't have any listing on the site!</h3>
<% end %>