config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Root path
  root to: 'pages#home'

  # User bookings list
  get '/booking/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
  get '/bookings', to: 'bookings#index', as: 'bookings'

  # User listings list
  get '/listings/user_listings', to: 'listings#user_listings', as: 'user_listings'
  get '/listing/by_action/:option', to: 'listings#list_by_action', as: 'list_by_action'


  # Furniture by ambiance
  get '/ambiances/:ambiance_id', to: 'ambiances#index', as: 'ambiances'

  # App routes
  get '/search', to: 'search#index', as: 'search'
  resources :listings do
      member do
        get '/approve', to: 'listings#approve_booking', as: 'approve'
        get '/reject', to: 'listings#reject_booking', as: 'reject'
        get '/rent', to: 'listings#rent_booking', as: 'rent'
        get '/finish', to: 'listings#finish_booking', as: 'finish'
      end

    resources :bookings, except: [:destroy, :new] do
      resources :payments, only: [:new, :create]
    end
    resources :furnitures
  end

  post '/listings/:listing_id/bookings/:booking_id/payments/new', to: 'payments#new'

  resources :deliveries, only: [:index, :show]
  get '/deliveries/accept/:id', to: 'deliveries#accept', as: 'accept_delivery'

  post '/listings/:listing_id/bookings/new', to: 'bookings#new', as: 'new_listing_booking'
  resources :bookings, only: [:destroy]

  # Messaging routes
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
        post :reply
        post :restore
        post :mark_as_read
      end
  end

  resources :messages, only: [:new, :create]
  get '/messages/listing/:listing_id/reject', to: 'messages#reject_booking', as: 'reject_booking_message'
  post '/messages/listing/:listing_id/send_message', to: 'messages#send_reject_message', as: 'send_reject_message'
  get '/messages/new/:user_id', to: 'messages#new_to', as: 'new_to'

  # App pages routes
  get '/about',   to: 'pages#about',   as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/team',    to: 'pages#team',    as: 'team'

  # Devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # Addresses routes for facebook users
  resources :addresses, only: [:new, :create]

  # Attachinary
  mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible flash-over" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible flash-over" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    setTimeout(function() {
      $('.alert').fadeOut('fast');
    }, 2000);
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <ul class="list-inline">
      <li><%= link_to 'delivery', deliveries_path %></li>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'team', team_path %></li>
      <li><%= link_to 'contact', contact_path %></li>
    </ul>
  </div>
  <div class="footer-social">
    <ul class="list-inline">
      <li><a href="https://www.facebook.com/easymoveisapp"><i class="fa fa-facebook"></i></a></li>
      <li><a href="https://www.twitter.com/easymoveis"><i class="fa fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
    </ul>
  </div>
</div>

app/views/shared/_meta.html.erb
<!-- Meta Google -->
<meta name="description" content="EasyMoveis: find the furniture that fits your life, rent in a click, and receive in a week!">

<!-- Meta Facebook -->
<meta property="og:title" content="EasyMoveis - The furniture that fits your life">
<meta property="og:image" content=<%= image_path 'facebook-meta.jpg'%>>
<meta property="og:description" content="EasyMoveis: find the furniture that fits your life, rent in a click, and receive in a week!">
<meta property="og:site_name" content="EasyMoveis"/>

<!-- Meta Twitter -->
<meta name="twitter:card" content=<%= image_path 'facebook-meta.jpg'%>>
<meta name="twitter:site" content="@easymoveis">
<meta name="twitter:title" content="EasyMoveis - The furniture that fits your life">
<meta name="twitter:description" content="EasyMoveis: find the furniture that fits your life, rent in a click, and receive in a week!">
<meta name="twitter:creator" content="@easymoveis">
<meta name="twitter:image:src" content=<%= image_path 'facebook-meta.jpg'%>>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to conversations_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-red"><%= current_user.mailbox.inbox({:read => false}).count %></div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <%= cl_image_tag avatar_image(current_user), width: 100, height: 100, crop: :fill, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to listings_path do %>
                <i class="fa fa-list"></i>  <%= t(".profile", default: "My listings") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-bed"></i>  <%= t(".profile", default: "My bookings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "LOGIN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "RENT YOUR FURNITURE!"), new_listing_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Rent furniture!", new_listing_path %></li>
          <li><%= link_to "My listings", user_listings_path %></li>
          <li><%= link_to "My bookings", user_bookings_path %></li>
          <li><%= link_to "My messages (#{current_user.mailbox.inbox({:read => false}).count})", conversations_path %></li>
          <li><%= link_to "Edit profile", edit_user_registration_path %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Sign out") %>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>